# <center> Module 2: Lesson 2 Data Exploration </center>
##  <center>Sample Data Exploration <br> with Pandas Library Functions </center>
<center>by: Nicole Woodland, P. Eng. for RoboGarden Inc. </center>

---

This notebook demonstrates multiple ways to perform data exploration on new datasets. Some process in data exploration include how to:
- Using summary statistics.
- Calculating Standard Deviation and variance with pandas.
- Arranging data using arrays in numpy.
- Calculating similarity/discimilarity.

Dataset: https://www.kaggle.com/datasets/crawford/80-cereals
Note: Modifications have been made to the original dataset to showcase the different functions.

In [1]:
import warnings
warnings.simplefilter('ignore')

In [7]:
# Import the data
import pandas as pd

df = pd.read_csv("../cereal_mod.csv")
len(df)

78

In [5]:
# View a few rows of the dataframe
df.head(6)

name mfr type  calories  protein  fat  fat.1  sodium  \
0                  100% Bran   N    C      70.0        4    1      1     130   
1          100% Natural Bran   Q    C     120.0        3    5      5      15   
2                   All-Bran   K  NaN      70.0        4    1      1     260   
3  All-Bran with Extra Fiber   K  NaN      50.0        4    0      0     140   
4             Almond Delight   R    C       NaN        2    2      2     200   
5    Apple Cinnamon Cheerios   G    C     110.0        2    2      2     180   

   fiber  carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0   10.0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    2.0    8.0       8     135         0      3     1.0  1.00  33.983679  
2    9.0    7.0       5     320        25      3     1.0  0.33  59.425505  
3   14.0    8.0       0     330        25      3     1.0  0.50  93.704912  
4    1.0   14.0       8      -1        25      3     1.0  0.75  34.384843  
5    1.5   10.5      10      70        25      1     1.0  0.75  29.509541

In [9]:
# See a table summary:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      78 non-null     object 
 1   mfr       78 non-null     object 
 2   type      75 non-null     object 
 3   calories  77 non-null     float64
 4   protein   78 non-null     int64  
 5   fat       78 non-null     int64  
 6   fat.1     78 non-null     int64  
 7   sodium    78 non-null     int64  
 8   fiber     78 non-null     float64
 9   carbo     78 non-null     float64
 10  sugars    78 non-null     int64  
 11  potass    78 non-null     int64  
 12  vitamins  78 non-null     int64  
 13  shelf     78 non-null     int64  
 14  weight    78 non-null     float64
 15  cups      78 non-null     float64
 16  rating    78 non-null     float64
dtypes: float64(6), int64(8), object(3)
memory usage: 10.5+ KB


In [11]:
# Get summary statistics:
df.describe()

calories    protein        fat      fat.1      sodium      fiber  \
count   77.000000  78.000000  78.000000  78.000000   78.000000  78.000000   
mean   106.753247   2.538462   1.000000   1.000000  161.346154   2.137179   
std     19.496394   1.089410   1.006473   1.006473   84.583291   2.371427   
min     50.000000   1.000000   0.000000   0.000000    0.000000   0.000000   
25%    100.000000   2.000000   0.000000   0.000000  131.250000   1.000000   
50%    110.000000   2.500000   1.000000   1.000000  180.000000   1.750000   
75%    110.000000   3.000000   1.750000   1.750000  217.500000   3.000000   
max    160.000000   6.000000   5.000000   5.000000  320.000000  14.000000   

           carbo     sugars      potass    vitamins      shelf     weight  \
count  78.000000  78.000000   78.000000   78.000000  78.000000  78.000000   
mean   14.679487   6.858974   95.294872   28.205128   2.192308   1.029231   
std     4.312451   4.450957   71.159252   22.200011   0.838330   0.149534   
min    -1.000000  -1.000000   -1.000000    0.000000   1.000000   0.500000   
25%    12.000000   3.000000   40.000000   25.000000   1.000000   1.000000   
50%    14.500000   6.500000   90.000000   25.000000   2.000000   1.000000   
75%    17.000000  11.000000  120.000000   25.000000   3.000000   1.000000   
max    23.000000  15.000000  330.000000  100.000000   3.000000   1.500000   

            cups     rating  
count  78.000000  78.000000  
mean    0.823333  42.706700  
std     0.232086  13.960470  
min     0.250000  18.042851  
25%     0.670000  33.376490  
50%     0.750000  40.424490  
75%     1.000000  50.812544  
max     1.500000  93.704912

### View summary statistics of numerical and categorical data
Numerical:

In [13]:
df["calories"].median()

110.0

In [15]:
df["calories"].mean()

106.75324675324676

In [17]:
df["calories"].std()

19.496393623434326

In [19]:
df["calories"].var()

380.1093643198906

### Correlation: 
How strongly different pairs of variables relate to each other
- 1: Perfect negative correlation. The variables tend to move in opposite directions (i.e., when one variable increases, the other variable decreases).
- 0: No correlation. The variables do not have a relationship with each other.
- 1: Perfect positive correlation. The variables tend to move in the same direction (i.e., when one variable increases, the other variable also increases).


![Correlation](https://upload.wikimedia.org/wikipedia/commons/3/34/Correlation_coefficient.png)

In [21]:
df.corr()

calories   protein       fat     fat.1    sodium     fiber  \
calories  1.000000  0.022417  0.500734  0.500734  0.288234 -0.289966   
protein   0.022417  1.000000  0.213201  0.213201 -0.063640  0.501887   
fat       0.500734  0.213201  1.000000  1.000000 -0.025171  0.022853   
fat.1     0.500734  0.213201  1.000000  1.000000 -0.025171  0.022853   
sodium    0.288234 -0.063640 -0.025171 -0.025171  1.000000 -0.079081   
fiber    -0.289966  0.501887  0.022853  0.022853 -0.079081  1.000000   
carbo     0.240576 -0.138324 -0.330632 -0.330632  0.374864 -0.359730   
sugars    0.562287 -0.318928  0.281207  0.281207  0.077265 -0.132995   
potass   -0.060124  0.551437  0.202186  0.202186 -0.048907  0.903082   
vitamins  0.266170  0.008261 -0.029062 -0.029062  0.352995 -0.031279   
shelf     0.100956  0.141107  0.277054  0.277054 -0.096190  0.302081   
weight    0.696981  0.217028  0.215728  0.215728  0.299856  0.248023   
cups      0.084042 -0.248094 -0.184029 -0.184029  0.132611 -0.515130   
rating   -0.690071  0.468233 -0.409436 -0.409436 -0.390484  0.581654   

             carbo    sugars    potass  vitamins     shelf    weight  \
calories  0.240576  0.562287 -0.060124  0.266170  0.100956  0.696981   
protein  -0.138324 -0.318928  0.551437  0.008261  0.141107  0.217028   
fat      -0.330632  0.281207  0.202186 -0.029062  0.277054  0.215728   
fat.1    -0.330632  0.281207  0.202186 -0.029062  0.277054  0.215728   
sodium    0.374864  0.077265 -0.048907  0.352995 -0.096190  0.299856   
fiber    -0.359730 -0.132995  0.903082 -0.031279  0.302081  0.248023   
carbo     1.000000 -0.345421 -0.359415  0.251655 -0.126421  0.129411   
sugars   -0.345421  1.000000  0.033592  0.126209  0.118738  0.449796   
potass   -0.359415  0.033592  1.000000  0.022207  0.370002  0.416407   
vitamins  0.251655  0.126209  0.022207  1.000000  0.297914  0.320571   
shelf    -0.126421  0.118738  0.370002  0.297914  1.000000  0.191817   
weight    0.129411  0.449796  0.416407  0.320571  0.191817  1.000000   
cups      0.372061 -0.042913 -0.499454  0.126451 -0.343757 -0.200728   
rating    0.055656 -0.756690  0.375718 -0.240859  0.020583 -0.298530   

              cups    rating  
calories  0.084042 -0.690071  
protein  -0.248094  0.468233  
fat      -0.184029 -0.409436  
fat.1    -0.184029 -0.409436  
sodium    0.132611 -0.390484  
fiber    -0.515130  0.581654  
carbo     0.372061  0.055656  
sugars   -0.042913 -0.756690  
potass   -0.499454  0.375718  
vitamins  0.126451 -0.240859  
shelf    -0.343757  0.020583  
weight   -0.200728 -0.298530  
cups      1.000000 -0.200052  
rating   -0.200052  1.000000

Categorical:

In [23]:
# Get frequency of values in column 'mfr'
frequency = df['mfr'].value_counts()
frequency

K    24
G    22
P     9
R     8
Q     8
N     6
A     1
Name: mfr, dtype: int64

In [25]:
# Calculate the mode:
df['mfr'].mode()

0    K
dtype: object

### Use numpy to anayze the data

Arrays and their shapes:

In [27]:
# Create an an array from a couple columns in our table:
array_cereal = df[["calories","fat"]].to_numpy()

In [29]:
array_cereal

array([[ 70.,   1.],
       [120.,   5.],
       [ 70.,   1.],
       [ 50.,   0.],
       [ nan,   2.],
       [110.,   2.],
       [110.,   0.],
       [130.,   2.],
       [ 90.,   1.],
       [ 90.,   0.],
       [120.,   2.],
       [110.,   2.],
       [120.,   3.],
       [110.,   2.],
       [110.,   1.],
       [110.,   0.],
       [100.,   0.],
       [100.,   0.],
       [110.,   0.],
       [110.,   1.],
       [110.,   3.],
       [100.,   0.],
       [110.,   0.],
       [100.,   1.],
       [100.,   0.],
       [110.,   1.],
       [110.,   0.],
       [100.,   0.],
       [120.,   2.],
       [120.,   0.],
       [110.,   1.],
       [100.,   0.],
       [110.,   1.],
       [100.,   1.],
       [110.,   0.],
       [120.,   3.],
       [120.,   2.],
       [110.,   1.],
       [110.,   0.],
       [110.,   1.],
       [140.,   1.],
       [110.,   1.],
       [100.,   2.],
       [110.,   1.],
       [100.,   1.],
       [150.,   3.],
       [150.,   3.],
       [160.,

In [31]:
print(array_cereal[0].mean())

35.5


In [33]:
# Check the number of dimensions
array_cereal.ndim

2

In [35]:
# check the number of rows
len(array_cereal)

78

In [37]:
# Check the number of rows and columns
array_cereal.shape

(78, 2)

In [67]:
# Take the first 5 values of the little array

array_cereal_1 = array_cereal[0:5]
print(array_cereal_1.shape)
array_cereal_1

(5, 2)


array([[ 70.,   1.],
       [120.,   5.],
       [ 70.,   1.],
       [ 50.,   0.],
       [ nan,   2.]])

In [69]:
# Reshape this data into 5 columns and two rows
array_cereal_1.reshape(2,5)
array_cereal_1

array([[ 70.,   1.],
       [120.,   5.],
       [ 70.,   1.],
       [ 50.,   0.],
       [ nan,   2.]])

### Join & Split Arrays

In [83]:
import numpy as np
array_cereal_2 = array_cereal[5:6]
print(array_cereal_1.shape,array_cereal_2.shape)

new_array = np.concatenate((array_cereal_1, array_cereal_2), axis = 0)
print("Joined array:", new_array.shape)

(5, 2) (1, 2)
Joined array: (6, 2)


### Filtering on Arrays

In [75]:
new_array

array([[ 70.,   1.],
       [120.,   5.],
       [ 70.,   1.],
       [ 50.,   0.],
       [ nan,   2.],
       [110.,   2.]])

In [77]:
new_array >= 5

array([[ True, False],
       [ True,  True],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False]])

In [79]:
new_array [new_array >= 5] = 0
new_array

array([[ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [nan,  2.],
       [ 0.,  2.]])